$schema: "http://json-schema.org/draft-07/schema#"
description: Snakemake configuration file

type: object
properties:
  dataset_name:
    type: string
  base_dataset_name:
    type: string
  base_table_filename:
    type: string

  results_basedir:
    type: string
  log_basedir:
    type: string

  det_pval_thresh:
    type: number

  noise_config_file:
    type: string

  gaia:
    type: object
    properties:
      credentials_file:
        type: string
      user:
        type: string
      password:
        type: string
