channels:
  - conda-forge
dependencies:
  - python =3.9
  - git =2.23.0
  - curl =7.71.1
  - tar =1.34
  - open-fonts =0.7.0
  - numpy =1.20
  - scipy =1.6
  - matplotlib =3.3
  - jupyter =1.0
  - jupyterlab =3.0
  - jupytext =1.10
  - astropy =4.2
  - astroquery =0.4
  - fitsio =1.1.4
  - pandas
  - pyyaml =5.4.1
  - tar =1.34
  - pip =21.0
  - pip:
      - kepler.py==0.0.6
      - jax<0.2.21
      - numpyro==0.8.0
      - tensorflow-probability==0.14.1
